/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */

export const FoodDishesColor1 = () : string => `<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 21.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 64 64" style="enable-background:new 0 0 64 64;" xml:space="preserve">
<style type="text/css">
	.st0{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;}
	.st1{fill:#F06A54;}
	.st2{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-miterlimit:10;}
	.st3{fill:#849B3B;}
	.st4{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke-dasharray:1.000000e-02,7;}
</style>
<title>Asset 1</title>
<g id="Layer_1-2">
	<g id="_Group_">
		<g id="_Group_2">
			<g id="_Group_3">
				<g id="_Group_4">
					<path id="_Path_" class="st0" d="M4.6,31.5V18.3c0-1.3,1.1-2.4,2.4-2.4h18.4c1.3,0,2.4,1.1,2.4,2.4v5.4"/>
					<path id="_Rectangle_" class="st0" d="M12,10.3h8.3c2.5,0,4.6,2,4.6,4.6v1.1l0,0H7.4l0,0v-1.1C7.4,12.3,9.5,10.3,12,10.3z"/>
					<path id="_Path_2" class="st0" d="M14.4,2.5l-3.5,7.8h10.6L18,2.5c-0.4-1-1.5-1.5-2.5-1.1C15,1.6,14.6,2,14.4,2.5z"/>
					<path id="_Path_3" class="st1" d="M7.5,18.9v10.6c0.6-0.5,5.4-5.6,17.4-5.7v-5H7.5z"/>
				</g>
				<g id="_Group_5">
					<path id="_Path_4" class="st2" d="M37.6,25.5c0,0,4.2,0.6,7.1-1.7c-1.5-1.8-3.4-3.2-5.5-4c2.2-1.1,4.2-2.4,6.1-3.9
						c-1.2-0.7-1.8-2.1-1.3-3.4l0.4-1.3l-1.5,0.1c-1.3,0-2.6-0.8-2.9-2.1c-1.7,1.1-5.5,4.4-5.5,4.4c-0.3-2.1-1.1-4.1-2.3-5.9
						c-1.7,1.5-2.9,3.5-3.3,5.7"/>
				</g>
			</g>
			<g id="_Group_6">
				<path id="_Path_5" class="st2" d="M50.9,37.7c2.5-0.4,4.8-1.3,6.9-2.7c0.5-0.3,1.1-0.5,1.7-0.5c1.7,0.1,3,1.4,3.1,3.1
					c0,1.7-1.4,3.2-3.1,3.2c0,0,0,0,0,0"/>
				<line id="_Path_6" class="st2" x1="1.5" y1="37.7" x2="8.1" y2="37.7"/>
				<path id="_Path_7" class="st3" d="M13.8,34.6c-0.8,0-1.6,0.3-2.2,0.9c-0.2,0.2-0.3,0.4-0.5,0.6c1.4-0.5,2.9,0.3,3.4,1.7
					c0.3,1,0.1,2.1-0.6,2.8c-0.1,0.1-0.2,0.2-0.3,0.3h0.2c1.7,0,3.1-1.4,3.1-3.1C16.9,36,15.5,34.6,13.8,34.6L13.8,34.6z"/>
				<path id="_Path_8" class="st2" d="M26,42.3c2.5,1.9,6.1,1.4,8-1.2c1.9-2.5,1.4-6.1-1.2-8c-2-1.5-4.8-1.5-6.8,0"/>
				<path id="_Path_9" class="st3" d="M29.5,34.6c-0.8,0-1.6,0.3-2.2,0.9c-0.2,0.2-0.3,0.4-0.5,0.6c1.4-0.5,3,0.2,3.5,1.6
					c0.4,1,0.1,2.1-0.7,2.8c-0.1,0.1-0.2,0.2-0.3,0.3h0.2c1.7,0,3.1-1.4,3.1-3.1S31.2,34.6,29.5,34.6L29.5,34.6L29.5,34.6z"/>
				<path id="_Path_10" class="st3" d="M45.2,34.6c-0.8,0-1.6,0.3-2.2,0.9c-0.2,0.2-0.3,0.4-0.5,0.6c1.4-0.5,2.9,0.3,3.4,1.7
					c0.3,1,0.1,2.1-0.6,2.8c-0.1,0.1-0.2,0.2-0.3,0.3h0.2c1.7,0,3.1-1.4,3.1-3.1C48.3,36,46.9,34.6,45.2,34.6L45.2,34.6z"/>
				<path id="_Rectangle_2" class="st1" d="M37.3,32L37.3,32c1.2,0,2.1,1,2.1,2.1v7.1c0,1.2-1,2.1-2.1,2.1h0c-1.2,0-2.1-1-2.1-2.1
					v-7.1C35.2,33,36.1,32,37.3,32z"/>
				<path id="_Path_11" class="st2" d="M41.9,42.4c2.6,1.8,6.2,1.1,7.9-1.5c1.8-2.6,1.1-6.2-1.5-7.9c-1.9-1.3-4.5-1.3-6.4,0"/>
				<path id="_Path_12" class="st2" d="M9.8,33.7c2.2-2.2,5.8-2.2,8,0c2.2,2.2,2.2,5.8,0,8c-2.2,2.2-5.8,2.2-8,0"/>
				<path id="_Rectangle_3" class="st1" d="M21.6,32L21.6,32c1.2,0,2.1,1,2.1,2.1v7.1c0,1.2-1,2.1-2.1,2.1l0,0c-1.2,0-2.1-1-2.1-2.1
					v-7.1C19.5,33,20.4,32,21.6,32z"/>
			</g>
			<g id="_Group_7">
				<path id="_Rectangle_4" class="st1" d="M16,58.7h32.2l0,0l0,0c0,2.5-2.1,4.6-4.6,4.6h-23C18.1,63.3,16,61.2,16,58.7L16,58.7
					L16,58.7z"/>
				<path id="_Path_13" class="st3" d="M32,58.7H16c-9.8,0-9.5-7-9.5-7H3.3c-1,0-1.8-0.8-1.8-1.8l0,0c0-1,0.8-1.8,1.8-1.8
					c0,0,0,0,0,0h57.4c1,0,1.8,0.8,1.8,1.8l0,0c0,1-0.8,1.8-1.8,1.8h-3.2c0,0,0.2,7-9.5,7L32,58.7z"/>
				<path id="_Path_14" class="st2" d="M32,58.7H16c-9.8,0-9.5-7-9.5-7H3.3c-1,0-1.8-0.8-1.8-1.8l0,0c0-1,0.8-1.8,1.8-1.8
					c0,0,0,0,0,0h57.4c1,0,1.8,0.8,1.8,1.8l0,0c0,1-0.8,1.8-1.8,1.8h-3.2c0,0,0.2,7-9.5,7L32,58.7z"/>
			</g>
			<path id="_Path_15" class="st4" d="M53.4,33.2c-2.4-4.5-8-6.2-12.5-3.9c-1.2-0.8-2.6-1.2-4-1c-1.1,0-2.2,0.4-3.2,1.1
				c-2.7-1.4-5.9-1.4-8.5,0c-1.2-0.8-2.6-1.2-4-1c-1.2,0-2.3,0.3-3.2,1"/>
		</g>
	</g>
</g>
</svg>
`;
  export const FoodDishesColor10 = () : string => `<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 21.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 64 64" style="enable-background:new 0 0 64 64;" xml:space="preserve">
<style type="text/css">
	.st0{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;}
	.st1{fill:#F7CF13;}
	.st2{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke-dasharray:1.000000e-02,7;}
	.st3{fill:#F06A54;}
	.st4{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-miterlimit:10;}
</style>
<title>Asset 10</title>
<g id="Layer_2">
	<g id="Layer_1-2">
		<g id="_Group_">
			<g id="_Group_2">
				<g id="_Group_3">
					<path id="_Rectangle_" class="st0" d="M31.2,2.6h0.2c2.9,0,5.3,2.4,5.3,5.3v0.2c0,2.9-2.4,5.3-5.3,5.3h-0.2
						c-2.9,0-5.3-2.4-5.3-5.3V7.8C25.9,4.9,28.3,2.6,31.2,2.6z"/>
					<circle id="_Ellipse_" class="st1" cx="31.3" cy="8" r="2.9"/>
				</g>
				<line id="_Path_" class="st2" x1="39.7" y1="20" x2="63" y2="30.9"/>
				<line id="_Path_2" class="st0" x1="61.5" y1="34.1" x2="18.1" y2="13.8"/>
				<line id="_Path_3" class="st0" x1="34.8" y1="18.4" x2="44.5" y2="13.8"/>
				<line id="_Path_4" class="st0" x1="1.1" y1="34.1" x2="27.8" y2="21.6"/>
				<g id="_Group_4">
					<path id="_Path_5" class="st0" d="M29.7,35.8c0-3.4-2.7-6.1-6.1-6.1c-3.4,0-6.1,2.7-6.1,6.1c0,0,0,0,0,0"/>
					<circle id="_Path_6" class="st3" cx="23.6" cy="35.8" r="2.2"/>
				</g>
				<g id="_Group_5">
					<path id="_Path_7" class="st0" d="M46.2,35.8c0-3.4-2.7-6.1-6.1-6.1S34,32.4,34,35.8"/>
					<circle id="_Path_8" class="st3" cx="40.1" cy="35.8" r="2.2"/>
				</g>
				<g id="_Group_6">
					<circle id="_Path_9" class="st0" cx="15.4" cy="44.8" r="6.1"/>
					<circle id="_Path_10" class="st3" cx="15.4" cy="44.8" r="2.2"/>
				</g>
				<g id="_Group_7">
					<circle id="_Path_11" class="st0" cx="31.8" cy="44.8" r="6.1"/>
					<circle id="_Path_12" class="st3" cx="31.8" cy="44.8" r="2.2"/>
				</g>
				<g id="_Group_8">
					<circle id="_Path_13" class="st0" cx="48.3" cy="44.8" r="6.1"/>
					<circle id="_Path_14" class="st3" cx="48.3" cy="44.8" r="2.2"/>
				</g>
				<g id="_Group_9">
					<g id="_Group_10">
						<path id="_Path_15" class="st1" d="M56.7,54.5h3.2c1,0,1.8-0.8,1.8-1.8l0,0c0-1-0.8-1.8-1.8-1.8h-57c-1,0-1.8,0.8-1.8,1.8l0,0
							c0,1,0.8,1.8,1.8,1.8H6l2,4c0.9,1.8,2.8,3,4.8,3h36.9c2,0,3.9-1.1,4.8-3L56.7,54.5z"/>
					</g>
					<g id="_Group_11">
						<path id="_Path_16" class="st4" d="M56.7,54.5h3.2c1,0,1.8-0.8,1.8-1.8l0,0c0-1-0.8-1.8-1.8-1.8h-57c-1,0-1.8,0.8-1.8,1.8l0,0
							c0,1,0.8,1.8,1.8,1.8H6l2,4c0.9,1.8,2.8,3,4.8,3h36.9c2,0,3.9-1.1,4.8-3L56.7,54.5z"/>
					</g>
					<line id="_Line_" class="st4" x1="6" y1="54.5" x2="15.4" y2="54.5"/>
				</g>
			</g>
		</g>
	</g>
</g>
</svg>
`;
  export const FoodDishesColor11 = () : string => `<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 21.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 64 64" style="enable-background:new 0 0 64 64;" xml:space="preserve">
<style type="text/css">
	.st0{fill:#DDDDCB;}
	.st1{fill:#F1EDDB;}
	.st2{fill:none;stroke:#262525;stroke-width:2.5;stroke-linecap:round;stroke-linejoin:round;stroke-dasharray:1.000000e-02,7;}
	.st3{fill:none;stroke:#262525;stroke-width:2.5;stroke-linecap:round;stroke-linejoin:round;}
	.st4{fill:none;stroke:#262525;stroke-width:2.5;stroke-linecap:round;stroke-miterlimit:10;}
	.st5{fill:#F7CF13;}
	.st6{fill:#FBAB1A;}
</style>
<title>Asset 11</title>
<g id="Layer_2">
	<g id="Layer_1-2">
		<g id="_Group_">
			<g id="_Group_2">
				<path id="_Path_" class="st0" d="M17.9,58.2v0.1c-0.5,1.5,0.4,3.2,1.9,3.6c0.3,0.1,0.5,0.1,0.8,0.1h20.8c1.6,0,2.9-1.3,2.9-2.9
					c0-0.3,0-0.6-0.1-0.9v-0.1"/>
				<path id="_Path_2" class="st1" d="M3.4,39.1c0,0,0.6,14.1,14.5,19.1h26.2c13.9-5,14.5-19,14.5-19"/>
				<path id="_Path_3" class="st2" d="M62.4,39.2c0,0.6-0.7,14.6-14,21.2"/>
				<path id="_Path_4" class="st3" d="M3.4,39.1c0,0,0.6,14.1,14.5,19.1h26.2c13.9-5,14.5-19,14.5-19"/>
				<g id="_Group_3">
					<g id="_Group_4">
						<path id="_Path_5" class="st4" d="M32.8,29.9c-2.1-3.3-4.5-6.3-7.2-9.1c-4-3.9-8.5-7.2-13.4-9.8c0.4-1.9-0.8-3.8-2.7-4.3
							C7.5,6.4,5.6,7.6,5.2,9.5c-0.3,1.2,0.1,2.5,0.9,3.3L6.4,13c-2-0.1-3.7,1.3-3.8,3.3c-0.1,1.4,0.6,2.7,1.9,3.4
							c-1.9,0.5-3,2.4-2.5,4.4c0.4,1.6,1.8,2.6,3.4,2.7c-1,0.7-1.5,1.7-1.5,2.9"/>
						<path id="_Path_6" class="st5" d="M10.4,15.4C8.2,20.2,8.8,25.7,11.8,30c-1.6-6.1,4.1-9,9.6-6.6c-3.2-3-6.8-5.6-10.7-7.7
							L10.4,15.4z"/>
					</g>
					<g id="_Group_5">
						<path id="_Path_7" class="st3" d="M27.8,16.1c1.5-1.5,3.9-1.5,5.3,0c0.3,0.3,0.5,0.5,0.6,0.9c0.5-2,2.6-3.2,4.6-2.7
							c1.6,0.4,2.8,1.9,2.8,3.6c1.3-1.6,3.6-1.9,5.3-0.7c1.2,0.9,1.7,2.5,1.3,3.9c1.7-1.1,4.1-0.7,5.2,1.1c0.8,1.3,0.8,2.9,0,4.2
							c2-0.6,4.1,0.5,4.7,2.5c0.1,0.3,0.1,0.6,0.2,0.8"/>
					</g>
					<g id="_Group_6">
						<path id="_Path_8" class="st3" d="M49.6,15.5c4.2-2.9,0.6-8.2-2.7-5.7c0.5-2-0.8-4.1-2.8-4.5c-1.5-0.3-3,0.2-3.9,1.4
							c-0.1-2.1-1.9-3.7-3.9-3.6c-1.6,0.1-3,1.2-3.5,2.8C32,4,29.8,3.1,27.9,3.8c-1.6,0.6-2.5,2.2-2.4,3.9c-1.4-1.2-3.5-1.3-4.9-0.1
							c-0.8,0.7-1.3,1.7-1.2,2.8c0,0.1,0,0.3,0,0.4"/>
					</g>
					<path id="_Path_9" class="st6" d="M29.6,20.3c0,0,5,5.3,7.2,9.7h15.5C47.1,22.8,38.4,19.1,29.6,20.3z"/>
				</g>
				<path id="_Path_10" class="st0" d="M58.6,39.1H3.3c-1.6,0-3-1.3-3-3c0,0,0,0,0,0l0,0c0-1.6,1.3-3,3-3c0,0,0,0,0,0h55.3
					c1.6,0,3,1.3,3,3c0,0,0,0,0,0l0,0C61.6,37.8,60.3,39.1,58.6,39.1C58.6,39.1,58.6,39.1,58.6,39.1z"/>
			</g>
		</g>
	</g>
</g>
</svg>
`;
  export const FoodDishesColor12 = () : string => `<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 21.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 64 58.9" style="enable-background:new 0 0 64 58.9;" xml:space="preserve">
<style type="text/css">
	.st0{fill:#FBAB1A;}
	.st1{fill:#DDDDCB;}
	.st2{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-miterlimit:10;}
	.st3{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke-dasharray:1.000000e-02,7;}
</style>
<title>Asset 12</title>
<g id="Layer_2">
	<g id="Layer_1-2">
		<g id="_Group_">
			<g id="_Group_2">
				<path id="_Path_" class="st0" d="M43.5,53.9v1.7c0,1.3-1.1,2.4-2.4,2.4H18.7c-1.3,0-2.4-1.1-2.4-2.4v-1.7"/>
				<path id="_Path_2" class="st1" d="M37.9,54h3.9c6.3,0,11.5-4.7,12.2-11c0-0.5,0-0.8,0-0.8h3c1,0,1.7-0.8,1.7-1.7l0,0
					c0-1-0.8-1.7-1.7-1.7H2.7c-1,0-1.7,0.8-1.7,1.7l0,0c0,1,0.8,1.7,1.7,1.7h3c0,0,0,0.3,0,0.8c0.7,6.3,6,11,12.3,11H37.9z"/>
				<path id="_Path_3" class="st2" d="M37.9,54h3.9c6.3,0,11.5-4.7,12.2-11c0-0.5,0-0.8,0-0.8h3c1,0,1.7-0.8,1.7-1.7l0,0
					c0-1-0.8-1.7-1.7-1.7H2.7c-1,0-1.7,0.8-1.7,1.7l0,0c0,1,0.8,1.7,1.7,1.7h3c0,0,0,0.3,0,0.8c0.7,6.3,6,11,12.3,11H37.9z"/>
				<path id="_Path_4" class="st3" d="M17.7,5.1c8.1-3.9,17.4-4.3,25-0.9c5.6,2.5,9.5,6.7,10.9,11.8"/>
				<path id="_Path_5" class="st2" d="M50.3,16.9C47.5,7,32.5,1.7,19.2,8.2c-1.8,0.8-3.4,1.9-4.8,3.2c-0.2,0.2-0.4,0.4-0.6,0.6"/>
				<path id="_Path_6" class="st2" d="M16.7,35l-8.1-0.1c-3.5,0-6.4-2.9-6.4-6.5c0-0.5,0.1-1,0.2-1.6c0.6-1.6,1.3-3.1,2.1-4.5
					l0.6,0.5c0.6,0.5,1.6,0.4,2-0.3c0-0.1,0.1-0.1,0.1-0.2c2.2-4.1,3.9-8.4,5-12.9c0,0,5.4,6.3,0,17"/>
				<path id="_Path_7" class="st2" d="M56,17.1v0.6l-15.7-2.1c-8.7-1.2-18.3,0.6-18.8,9.3C21.1,32.4,29.7,35,29.7,35"/>
				<path id="_Path_8" class="st2" d="M51.2,25.3c0,1.8-0.3,3.5-0.8,5.2c-0.4,1.5-1,3.1-1.8,4.5c-3.6-1.6-6.6-5-5.1-8.9
					c1.4-3.7,7.7-3.4,12.6-3.8v0.3c0,1.8,1.3,3.3,3,3.6c1.9,0.2,3.7-1.1,3.9-3c0.2-1.3-0.4-2.6-1.5-3.3c1.6-1.1,2-3.2,0.9-4.8
					c-1.1-1.6-3.2-2-4.8-0.9c-1,0.6-1.5,1.7-1.5,2.9c0,0,0,0,0,0.1"/>
				<path id="_Path_9" class="st0" d="M26.5,20.4c-3.2,2.7-3.6,8.9,3.6,11.8c-2.9-4.3-1.3-12,13.8-13.4
					C42.4,18.8,31.6,16.2,26.5,20.4z"/>
				<path id="_Path_10" class="st0" d="M20.5,10.7C19.2,11.3,18,12,17,12.9c0.5,2,0.7,4.1,0.5,6.2c2.5-3.4,10.1-11.4,24.9-8.1
					c-0.7-0.4-1.4-0.8-2.1-1.1C34.3,7.3,26.9,7.6,20.5,10.7z"/>
			</g>
		</g>
	</g>
</g>
</svg>
`;
  export const FoodDishesColor13 = () : string => `<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 21.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 62.9 64" style="enable-background:new 0 0 62.9 64;" xml:space="preserve">
<style type="text/css">
	.st0{fill:#ED6954;}
	.st1{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-miterlimit:10;}
	.st2{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;}
	.st3{fill:#FBAB1A;}
	.st4{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke-dasharray:1.000000e-02,7;}
</style>
<title>Asset 13</title>
<g id="Layer_2">
	<g id="Layer_1-2">
		<g id="_Group_">
			<g id="_Group_2">
				<path id="_Rectangle_" class="st0" d="M18.5,59.3h29.4l0,0l0,0c0,2.3-1.9,4.2-4.2,4.2h-21C20.4,63.5,18.5,61.6,18.5,59.3
					L18.5,59.3L18.5,59.3z"/>
				<path id="_Path_" class="st1" d="M52,49.6h7.3c0.9,0,1.7,0.7,1.7,1.7c0,0,0,0,0,0l0,0c0,0.9-0.7,1.7-1.7,1.7c0,0,0,0,0,0h-2.9
					c0,0,0.2,6.4-8.7,6.4H18.5c-8.9,0-8.7-6.4-8.7-6.4H6.9c-0.9,0-1.7-0.7-1.7-1.7l0,0l0,0c0-0.9,0.7-1.7,1.7-1.7c0,0,0,0,0,0h7.4"
					/>
				<g id="_Group_3">
					<path id="_Path_2" class="st1" d="M14.8,42.2l-4.1-0.6c-0.3,0-0.5-0.3-0.5-0.7c0-0.1,0.1-0.2,0.1-0.3l2.5-2.8l2.5-2.8
						c0.2-0.2,0.6-0.2,0.8,0c0.1,0.1,0.1,0.2,0.2,0.3l1.1,4"/>
					<g id="_Group_4">
						<path id="_Path_3" class="st1" d="M46.3,42.6c0.7,0.6,1.2,1.4,1.4,2.3"/>
					</g>
					<g id="_Group_5">
						<path id="_Path_4" class="st1" d="M43.3,44.9c0.6,0.7,1,1.6,1,2.5"/>
					</g>
					<g id="_Group_6">
						<path id="_Path_5" class="st1" d="M40.1,46.7c0.5,0.8,0.7,1.7,0.6,2.6"/>
					</g>
					<path id="_Path_6" class="st1" d="M15.9,47.1c9.4,9.5,24.6,9.6,34.1,0.2c0.1-0.1,0.2-0.2,0.2-0.2c1.9-1.9,1.9-5-0.1-6.9
						c-0.3-0.3-0.6-0.5-1-0.8l-0.1,0c-1.9-1.1-4.4-0.8-5.9,0.8c-5.5,5.6-14.6,5.6-20.1,0.1c0,0-0.1-0.1-0.1-0.1
						c-1.5-1.6-4-2-5.9-0.8l-0.1,0c-2.3,1.3-3.2,4.3-1.8,6.7C15.4,46.5,15.6,46.8,15.9,47.1z"/>
					<path id="_Path_7" class="st1" d="M51.4,42.2l4.1-0.6c0.3,0,0.5-0.3,0.5-0.7c0-0.1-0.1-0.2-0.1-0.3l-2.5-2.8L50.8,35
						c-0.2-0.2-0.6-0.2-0.8,0c-0.1,0.1-0.1,0.2-0.2,0.3l-1.1,4"/>
					<path id="_Path_8" class="st0" d="M29.6,47.3c-3.4-0.7-6.5-2.4-8.9-4.8c-0.5-0.6-1.4-0.7-2.1-0.3h-0.1
						c-0.4,0.3-0.8,0.7-0.8,1.2c-0.1,0.5,0.1,1.1,0.5,1.4c2.4,2.5,5.3,4.3,8.6,5.3C27.5,49,28.5,48,29.6,47.3z"/>
				</g>
				<g id="_Group_7">
					<path id="_Path_9" class="st2" d="M5.3,38.5V31c0-3.7,3-6.6,6.6-6.6l0,0h2.5"/>
					<line id="_Path_10" class="st2" x1="14.4" y1="29.9" x2="14.4" y2="21"/>
					<line id="_Path_11" class="st2" x1="40.3" y1="19.8" x2="40.3" y2="36.7"/>
					<path id="_Path_12" class="st1" d="M35.2,18.4c1.1,1.7,3.2,2.3,5,1.4c1.8-0.8,3-2.6,3.1-4.6c0-2.7-2.2-4.9-4.9-4.9H38
						c-0.4-3.5-3.6-5.9-7-5.5c-2,0.2-3.7,1.4-4.7,3.1c-1.8-1.9-4.7-2-6.6-0.2c-1,0.9-1.5,2.2-1.5,3.5c0,0.1,0,0.1,0,0.2
						c-2.8-0.7-5.6,0.9-6.4,3.7c-0.1,0.4-0.2,0.9-0.2,1.4c0,1.9,1,3.7,2.7,4.6c1.7,0.8,3.7,0.2,4.7-1.3"/>
					<path id="_Path_13" class="st1" d="M26.3,7.9c0,0,2.2,2.5,0.2,4.9"/>
					<path id="_Path_14" class="st2" d="M38,10.4c-1,0.1-1.9,0.8-2.5,1.7"/>
					<path id="_Path_15" class="st3" d="M35.1,39.8V26.6c0.1-0.8-0.6-1.6-1.4-1.6c-0.8-0.1-1.6,0.6-1.6,1.4c0,0.1,0,0.2,0,0.2V40
						c0.3,0,0.7,0,1,0C33.8,40,34.5,39.9,35.1,39.8z"/>
					<path id="_Path_16" class="st3" d="M28.8,26.6c-0.1-0.8-0.8-1.5-1.6-1.4c-0.7,0.1-1.3,0.7-1.4,1.4v10.8c0.9,0.7,1.9,1.4,3,1.8
						V26.6z"/>
					<path id="_Path_17" class="st3" d="M22.5,26.6c0-0.8-0.7-1.5-1.5-1.5l0,0c-0.8,0-1.5,0.7-1.5,1.5v7.7c1,0,2.1,0.2,3,0.7
						L22.5,26.6z"/>
				</g>
				<path id="_Compound_Path_" class="st4" d="M9.8,21.2c-4.6,1-7.9,5-7.9,9.7v7.6 M43.6,21.6c1.9-1.6,3-3.9,3.1-6.3
					c0-3.7-2.5-7-6.1-8c-2.1-4.9-7.8-7.1-12.7-5c-0.8,0.3-1.6,0.8-2.3,1.4"/>
			</g>
		</g>
	</g>
</g>
</svg>
`;
  export const FoodDishesColor14 = () : string => `<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 21.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 64 64" style="enable-background:new 0 0 64 64;" xml:space="preserve">
<style type="text/css">
	.st0{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke-dasharray:1.000000e-02,7;}
	.st1{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;}
	.st2{fill:#849B3B;}
	.st3{fill:#F06A54;}
</style>
<title>Asset 14</title>
<g id="Layer_2">
	<g id="Layer_1-2">
		<g id="_Group_">
			<g id="_Group_2">
				<g id="_Group_3">
					<path id="_Compound_Path_" class="st0" d="M50,14.3c0,0.5,0,0.9,0,1.4c0,3-0.6,5.9-1.9,8.6"/>
					<path id="_Compound_Path_2" class="st1" d="M21.8,25.9c-2.6-2.8-4-6.4-3.9-10.2c0-2,0.4-4.1,1.3-5.9 M26,13.9
						c-0.2,0.6-0.3,1.1-0.3,1.7c0,3.8,2.4,6.3,5.5,7.7 M27.7,11.1c2.5-2.4,6.4-2.2,8.8,0.3c0.7,0.7,1.2,1.6,1.4,2.5 M21.2,6.6
						c5-6,13.9-6.8,19.9-1.8c1.6,1.3,2.9,3,3.8,4.9 M45.9,13c0.2,0.9,0.3,1.8,0.3,2.7c0,4.2-1.7,8.3-4.8,11.1
						c-1.5,1.4-3.3,2.6-5.2,3.5"/>
					<path id="_Path_" class="st1" d="M42.2,15.2c0,0.2,0,0.3,0,0.5c0,16.4-29.8,14.5-29.8,14.5"/>
					<path id="_Path_2" class="st1" d="M24.4,8.9C28.2,4.7,34.6,4.3,38.8,8c1.2,1,2.1,2.3,2.6,3.7"/>
					<path id="_Path_3" class="st1" d="M26.5,24.8c-3-2.1-4.7-5.5-4.7-9.2c0-1.3,0.3-2.6,0.8-3.9"/>
					<path id="_Path_4" class="st1" d="M45.4,26.1c3.4,0.2,7.8,0,7.9,0"/>
					<path id="_Path_5" class="st1" d="M53.5,30.1c-3.5,0.1-7,0.1-10.5-0.2"/>
					<line id="_Line_" class="st1" x1="38" y1="13.9" x2="58.1" y2="1.5"/>
					<line id="_Line_2" class="st0" x1="15.2" y1="11.8" x2="3.9" y2="4.8"/>
					<line id="_Line_3" class="st1" x1="32" y1="17.6" x2="5.9" y2="1.5"/>
				</g>
				<g id="_Group_4">
					<path id="_Path_6" class="st2" d="M20.6,59.8v0.1c-0.5,1.4,0.3,3,1.7,3.5c0.3,0.1,0.6,0.1,0.8,0.1h19.7c1.5,0,2.8-1.2,2.8-2.7
						c0-0.3,0-0.6-0.1-0.9v-0.1"/>
					<path id="_Path_7" class="st3" d="M53.4,49.8c-5.5,1.4-11.3,1.5-16.8,0.3c-4.1-1-7.9-2.9-12-3.8c-5.4-1.1-11.1-0.2-15.9,2.4
						c2.2,5.2,6.6,9.2,11.9,11h24.9c5.3-1.8,9.7-5.8,11.9-11C56,49.2,54.7,49.5,53.4,49.8z"/>
					<path id="_Path_8" class="st0" d="M14.2,61C3.6,54.3,2.9,42.4,2.9,41.8"/>
					<path id="_Path_9" class="st1" d="M6.8,41.7c0,0,0.5,13.3,13.8,18.1h24.9C58.7,55,59.2,41.7,59.2,41.7"/>
					<path id="_Path_10" class="st2" d="M59.2,41.7H6.7c-1.6,0-2.8-1.2-2.8-2.8c0,0,0,0,0,0l0,0c0-1.6,1.3-2.8,2.8-2.8h52.5
						c1.5,0,2.8,1.3,2.8,2.8l0,0C62,40.4,60.8,41.7,59.2,41.7z"/>
				</g>
			</g>
		</g>
	</g>
</g>
</svg>
`;
  export const FoodDishesColor15 = () : string => `<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 21.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 64 64" style="enable-background:new 0 0 64 64;" xml:space="preserve">
<style type="text/css">
	.st0{fill:#FBAB1A;}
	.st1{fill:#DDDDCB;}
	.st2{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-miterlimit:10;}
	.st3{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke-dasharray:1.000000e-02,7;}
</style>
<title>Asset 15</title>
<g id="Layer_2">
	<g id="Layer_1-2">
		<g id="_Group_">
			<g id="_Group_2">
				<path id="_Path_" class="st0" d="M46.6,55v1.8c0,1.4-1.2,2.6-2.6,2.6H20c-1.4,0-2.6-1.2-2.6-2.6V55"/>
				<path id="_Path_2" class="st1" d="M44.7,55.1c6.7,0,12.4-5.1,13.1-11.8c0-0.5,0-0.8,0-0.8h3.2c1,0,1.9-0.8,1.9-1.8c0,0,0,0,0,0
					l0,0c0-1-0.8-1.9-1.9-1.9H2.9c-1,0-1.9,0.8-1.9,1.9l0,0c0,1,0.8,1.9,1.9,1.9h3.2c0,6.3,5.7,12.6,13.2,12.6L44.7,55.1L44.7,55.1z
					"/>
				<path id="_Path_3" class="st2" d="M44.7,55.1c6.7,0,12.4-5.1,13.1-11.8c0-0.5,0-0.8,0-0.8h3.2c1,0,1.9-0.8,1.9-1.8c0,0,0,0,0,0
					l0,0c0-1-0.8-1.9-1.9-1.9H2.9c-1,0-1.9,0.8-1.9,1.9l0,0c0,1,0.8,1.9,1.9,1.9h3.2c0,6.3,5.7,12.6,13.2,12.6L44.7,55.1L44.7,55.1z
					"/>
				<path id="_Path_4" class="st3" d="M2.5,35.6c0-4.2,1.6-8.3,4.3-11.5"/>
				<path id="_Path_5" class="st2" d="M6.1,35.7c0-3.4,1.2-6.6,3.4-9.2c1.5-1.6,2.1-3.9,1.7-6.1c-0.4-1.1,0.3-2.4,1.4-2.7
					c0.1,0,0.1,0,0.2-0.1l3.2-0.7c1.2-0.2,2.3,0.5,2.6,1.7c0,0,0,0,0,0l0,0.2c0.5,2.1,2,3.9,4,4.8c4.5,2.3,7.6,6.8,8.1,11.9"/>
				<path id="_Path_6" class="st2" d="M12.4,17.8l-1.3-6.3c-1.4,0.2-2.7-0.9-2.8-2.3c-0.2-1.4,0.9-2.7,2.3-2.8
					c0.6-0.1,1.2,0.1,1.7,0.4C13,5.6,14.6,5.2,15.8,6s1.6,2.4,0.8,3.6c-0.3,0.5-0.9,0.9-1.5,1.1l1.3,6.3"/>
				<path id="_Path_7" class="st3" d="M51.4,16.7c3.7,2.5,8.5,5.8,9.8,16"/>
				<path id="_Path_8" class="st2" d="M22.4,22.9c6.1-8.5,14.2-2.5,22.2-7.7c3.6,6.5,13.3,4.4,13.3,23.7"/>
				<path id="_Path_9" class="st2" d="M27.7,28c4-4.5,14.4-4.5,16.4,3.2"/>
				<path id="_Path_10" class="st2" d="M53.3,35.7c0-6.2-6.1-9.9-10.6-7.3"/>
				<path id="_Path_11" class="st0" d="M21.4,26.3c-2.4-1.1-4.2-3.1-5.1-5.5c-0.2-0.6-0.9-0.9-1.5-0.6c-0.4,0.2-0.7,0.6-0.7,1.1
					c0.1,2.6-0.8,5.2-2.5,7.1c-1.8,2.1-2.7,4.7-2.7,7.4c0,0,4.7-7.3,16.1-6.7C24,27.9,22.8,27,21.4,26.3z"/>
			</g>
		</g>
	</g>
</g>
</svg>
`;
  export const FoodDishesColor2 = () : string => `<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 21.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 64 64" style="enable-background:new 0 0 64 64;" xml:space="preserve">
<style type="text/css">
	.st0{fill:#FBAB1A;}
	.st1{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke-dasharray:1.000000e-02,7;}
	.st2{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;}
	.st3{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-miterlimit:10;}
	.st4{fill:#F26756;}
</style>
<title>Asset 2</title>
<g id="Layer_2">
	<g id="Layer_1-2">
		<g id="_Group_">
			<path id="_Path_" class="st0" d="M29.9,55.1C17.1,55.1,6.8,44.7,6.8,32S17.2,8.9,29.9,8.9c2.2,0,4.5,0.3,6.6,1
				c-0.4,1.2-1.7,5-5.6,16.8c-0.3,1-0.2,2.2,0.5,3.1c0.6,0.9,1.7,1.4,2.8,1.4l0,0c0.3,0,0.6,0,0.9-0.1l17.2-4.5
				c3,12.4-4.5,24.9-16.9,27.9C33.6,54.9,31.8,55.1,29.9,55.1z"/>
			<path id="_Path_2" class="st1" d="M8.6,9.4c8.1-7.6,19.6-10.3,30.2-7.1"/>
			<path id="_Path_3" class="st1" d="M28.9,63c-8.2-0.2-16-3.7-21.6-9.8"/>
			<path id="_Path_4" class="st2" d="M56.3,25c3.9,14.6-4.8,29.6-19.4,33.5S7.3,53.7,3.4,39S8.2,9.4,22.8,5.5
				c4.9-1.3,10.1-1.2,14.9,0.2"/>
			<path id="_Path_5" class="st3" d="M20,36.7c0,1.8-1.4,3.2-3.2,3.2s-3.2-1.4-3.2-3.2c0-1.8,1.4-3.2,3.2-3.2"/>
			<circle id="_Path_6" class="st4" cx="46" cy="34.9" r="2"/>
			<circle id="_Path_7" class="st0" cx="41.9" cy="20.8" r="1.7"/>
			<circle id="_Path_8" class="st0" cx="44.9" cy="12.8" r="2.1"/>
			<path id="_Path_9" class="st3" d="M29.9,15.4c0,1.1-0.9,2.1-2.1,2.1c-1.1,0-2.1-0.9-2.1-2.1c0,0,0,0,0,0"/>
			<circle id="_Path_10" class="st4" cx="24.7" cy="30.6" r="2.2"/>
			<path id="_Path_11" class="st3" d="M31.2,41.6c-1.1-1.2-1-3.1,0.2-4.2c1.2-1.1,3.1-1,4.2,0.2c0.1,0.1,0.2,0.2,0.2,0.3"/>
			<circle id="_Path_12" class="st4" cx="25.4" cy="47.1" r="2.9"/>
			<path id="_Path_13" class="st4" d="M21.2,23.6c0.8-0.9,0.5-2.4-0.6-3.5c-1.2-1.1-2.8-1.3-3.6-0.5c-0.5,0.5-0.6,1.3-0.4,1.9
				l-1.5,1.5c-0.3,0.3-0.3,0.7,0,1c0,0,0,0,0,0l1.7,1.6c0.3,0.3,0.7,0.3,1,0c0,0,0,0,0,0l1.5-1.5C20,24.3,20.8,24.1,21.2,23.6z"/>
			<path id="_Path_14" class="st0" d="M51.5,20c1-0.4,1.3-1.8,0.8-3s-1.7-2-2.7-1.6c-0.5,0.3-0.9,0.8-1,1.4l-1.7,0.7
				c-0.3,0.1-0.4,0.5-0.3,0.8l0.8,1.9c0.1,0.3,0.5,0.4,0.8,0.3l1.7-0.7C50.3,20.1,50.9,20.2,51.5,20z"/>
			<path id="_Path_15" class="st4" d="M41.4,41.7c-0.7-0.8-2.1-0.7-3.2,0.2c-1.1,0.9-1.4,2.3-0.8,3.1c0.4,0.4,1,0.6,1.6,0.5l1.2,1.4
				c0.2,0.3,0.6,0.3,0.8,0.1l1.6-1.3c0.3-0.2,0.3-0.6,0.1-0.8l-1.2-1.4C41.9,42.8,41.8,42.2,41.4,41.7z"/>
			<g id="_Group_2">
				<path id="_Path_16" class="st2" d="M52.2,11c2.7,2.8,4.6,6.3,5.6,10.1l3.7-1c-2.4-9-9.2-16.2-18-19l-1.2,3.6
					C46.1,5.9,49.5,8.1,52.2,11z"/>
				<polyline id="_Path_17" class="st2" points="42.3,4.7 34.9,27.1 57.8,21.1 				"/>
			</g>
			<path id="_Path_18" class="st3" d="M29.9,55.1C17.1,55.1,6.8,44.7,6.8,32S17.2,8.9,29.9,8.9c2.2,0,4.5,0.3,6.6,1
				c-0.4,1.2-1.7,5-5.6,16.8c-0.3,1-0.2,2.2,0.5,3.1c0.6,0.9,1.7,1.4,2.8,1.4l0,0c0.3,0,0.6,0,0.9-0.1l17.2-4.5
				c3,12.4-4.5,24.9-16.9,27.9C33.6,54.9,31.8,55.1,29.9,55.1z"/>
		</g>
	</g>
</g>
</svg>
`;
  export const FoodDishesColor3 = () : string => `<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 21.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 64 64" style="enable-background:new 0 0 64 64;" xml:space="preserve">
<style type="text/css">
	.st0{fill:#8A9E3B;}
	.st1{fill:#F06A54;}
	.st2{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-miterlimit:10;}
	.st3{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke-dasharray:1.000000e-02,7;}
	.st4{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;}
</style>
<title>Asset 3</title>
<g id="Layer_2">
	<g id="Layer_1-2">
		<g id="_Group_">
			<g id="_Group_2">
				<path id="_Rectangle_" class="st0" d="M15.1,56.9h31.3l0,0l0,0c0,2.5-2,4.5-4.5,4.5H19.6C17.1,61.4,15.1,59.4,15.1,56.9
					L15.1,56.9L15.1,56.9z"/>
				<path id="_Path_" class="st1" d="M22.7,19.3c-2.4,2.6-3.3,6.3-2.4,9.7c0.4,1.4,0.9,2.4,0.6,3.8c-0.6,3.3,1.1,5,3.1,6.9
					c1.4,1.2,3.3,1.7,5.1,1.3l0.4-0.1c1.2-0.1,2.4,0.1,3.4,0.7c3.9,2,8.9,0.7,8.9,0.7c-1-1,1.1-3.4,1.1-3.4
					c4.5-5.3-5.3-14.7-5.3-14.7S28.3,14.5,23,19"/>
				<g id="_Group_3">
					<path id="_Path_2" class="st2" d="M19,15.5c0,0,0.3-4.2-2.3-7c-1.7,1.6-2.9,3.6-3.5,5.9c-1.3-2.1-2.8-4-4.5-5.8
						c-0.6,1.3-2,1.9-3.3,1.6L4,9.9c0.1,0.6,0.1,1.1,0.2,1.5c0.1,1.3-0.7,2.6-1.9,3.1c1.2,1.6,4.8,5.1,4.8,5.1
						c-2.1,0.5-4,1.5-5.7,2.8c1.6,1.6,3.7,2.6,5.9,2.8"/>
				</g>
				<path id="_Path_3" class="st2" d="M50.8,46.6h7.8c1,0,1.8,0.8,1.8,1.8v0l0,0c0,1-0.8,1.8-1.8,1.8c0,0,0,0,0,0h-3.1
					c0,0,0.2,6.8-9.3,6.8h-31c-9.5,0-9.3-6.8-9.3-6.8H2.8c-1,0-1.8-0.8-1.8-1.8c0,0,0,0,0,0l0,0c0-1,0.8-1.8,1.8-1.8c0,0,0,0,0,0H31
					"/>
				<path id="_Rectangle_2" class="st2" d="M15.1,56.9h31.3l0,0l0,0c0,2.5-2,4.5-4.5,4.5H19.6C17.1,61.4,15.1,59.4,15.1,56.9
					L15.1,56.9L15.1,56.9z"/>
				<path id="_Compound_Path_" class="st3" d="M51.7,13.6c5,0.7,12,5.1,11.2,14.3c-0.5,5.6-4.1,9.7-10.8,12.5"/>
				<path id="_Path_4" class="st4" d="M44,34.3c5.8-1.1,5.9-6.8,1.9-11.6c0,0,1.7-0.7,4.2,1.6c1.1,1.1,2.7,0.3,3-1.2
					c0.4-2-0.4-3.7-1.9-5.8c0,0,8.8,1.3,8,10.3c-0.7,7.5-9.7,10.2-16.3,11.5"/>
				<path id="_Path_5" class="st2" d="M27.6,18c1.1-5.8,6.8-6,11.6-1.9c0,0,0.7-1.7-1.6-4.2c-1.1-1.1-0.3-2.7,1.2-3
					c1.9-0.4,3.6,0.4,5.7,1.9c0,0-1.3-8.8-10.3-8c-7.5,0.7-10.4,10-11.6,16.6c-2.4,2.6-3.3,6.3-2.4,9.7c0.4,1.4,0.9,2.4,0.6,3.8
					c-0.6,3.3,1.1,5,3.1,6.9c1.4,1.2,3.3,1.7,5.1,1.3l0.4-0.1c1.2-0.1,2.4,0.1,3.4,0.7c3.9,2,8.9,0.7,8.9,0.7c-1-1,1.1-3.4,1.1-3.4
					c4.5-5.3-5.3-14.7-5.3-14.7S28.3,14.5,23,19"/>
				<path id="_Path_6" class="st2" d="M33.6,41.9c1.4,2.4,2.1,5.1,1.8,7.9"/>
				<path id="_Path_7" class="st2" d="M38.3,42.8c1.3,2.1,2,4.5,1.9,7"/>
				<path id="_Path_8" class="st2" d="M41.8,42.4l2.9,1.4c1.5,0.7,2.5,2.2,2.6,3.9l0,2.1"/>
				<path id="_Path_9" class="st2" d="M17.2,28.2l-1.7,1.7c1.2,1.2,1.2,3.1,0,4.2c-1.2,1.2-3.1,1.2-4.2,0l-5.7,5.7
					c4,4,10.4,4.3,14.9,0.8"/>
				<path id="_Path_10" class="st2" d="M10.2,16.8l2.6,3.2c1.7,2,1.4,5-0.6,6.7l0,0"/>
			</g>
		</g>
	</g>
</g>
</svg>
`;
  export const FoodDishesColor4 = () : string => `<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 21.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 64 64" style="enable-background:new 0 0 64 64;" xml:space="preserve">
<style type="text/css">
	.st0{fill:#849B3B;}
	.st1{fill:#F7CF13;}
	.st2{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke-dasharray:1.000000e-02,7;}
	.st3{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-miterlimit:10;}
</style>
<title>Asset 4</title>
<g id="Layer_2">
	<g id="Layer_1-2">
		<g id="_Group_">
			<g id="_Group_2">
				<path id="_Path_" class="st0" d="M46.6,54.8v1.8c0,1.4-1.2,2.6-2.6,2.6c0,0,0,0,0,0H20c-1.4,0-2.6-1.2-2.6-2.6v-1.9"/>
				<path id="_Path_2" class="st1" d="M40.6,55h4.1c6.7,0,12.4-5.1,13.1-11.8c0-0.5,0-0.8,0-0.8h3.2c1,0,1.9-0.8,1.9-1.8
					c0,0,0,0,0,0l0,0c0-1-0.8-1.9-1.8-1.9c0,0,0,0,0,0H2.9c-1,0-1.9,0.8-1.9,1.9c0,0,0,0,0,0l0,0c0,1,0.8,1.9,1.9,1.9h3.2
					c0,0,0,0.3,0,0.8C6.8,49.9,12.5,55,19.3,55H40.6z"/>
				<path id="_Path_3" class="st2" d="M14.2,57.7C8.7,56,4.4,51.5,3,45.9"/>
				<path id="_Path_4" class="st3" d="M40.6,55h4.1c6.7,0,12.4-5.1,13.1-11.8c0-0.5,0-0.8,0-0.8h3.2c1,0,1.9-0.8,1.9-1.8
					c0,0,0,0,0,0l0,0c0-1-0.8-1.9-1.8-1.9c0,0,0,0,0,0H2.9c-1,0-1.9,0.8-1.9,1.9c0,0,0,0,0,0l0,0c0,1,0.8,1.9,1.9,1.9h3.2
					c0,0,0,0.3,0,0.8C6.8,49.9,12.5,55,19.3,55H40.6z"/>
				<g id="_Group_3">
					<path id="_Path_5" class="st3" d="M21.3,23c0,0,1.2-3.9-0.6-7c-1.9,1.1-3.5,2.7-4.5,4.7c-0.8-2.2-1.7-4.3-2.9-6.3
						c-0.8,1-2.2,1.4-3.4,0.8l-1.2-0.6c0,0.6-0.1,1-0.2,1.4c-0.2,1.3-1.2,2.3-2.4,2.4c0.8,1.7,3.4,5.8,3.4,5.8c-2,0-4,0.5-5.9,1.4
						c1.1,1.8,2.8,3.2,4.8,3.9"/>
				</g>
				<path id="_Path_6" class="st3" d="M21.9,30.3c0.9,1.4,2.7,1.8,4,0.9c1.4-0.9,1.8-2.7,0.9-4l6.7-4.3c2.4,3.8,2.2,8.6-0.4,12.2"/>
				<path id="_Path_7" class="st3" d="M58.5,31.8l-3.1-5.6c-1.4,0.8-3.2,0.3-4-1.1c-0.8-1.4-0.3-3.2,1.1-4l-4-6.9
					c-4.8,2.8-6.8,8.7-4.5,13.8"/>
				<g id="_Group_4">
					<path id="_Path_8" class="st3" d="M6.2,38.7c0-4.4,3.6-8,8-8s8,3.6,8,8"/>
					<line id="_Line_" class="st3" x1="14.2" y1="33.8" x2="14.2" y2="34.8"/>
					<line id="_Line_2" class="st3" x1="10.8" y1="35.3" x2="11.4" y2="35.9"/>
					<line id="_Line_3" class="st3" x1="17.6" y1="35.3" x2="17" y2="35.9"/>
				</g>
				<g id="_Group_5">
					<path id="_Path_9" class="st3" d="M37.3,38.7c0-4.4,3.6-8,8-8s8,3.6,8,8"/>
					<line id="_Line_4" class="st3" x1="45.3" y1="33.8" x2="45.3" y2="34.8"/>
					<line id="_Line_5" class="st3" x1="41.8" y1="35.3" x2="42.5" y2="35.9"/>
					<line id="_Line_6" class="st3" x1="48.7" y1="35.3" x2="48" y2="35.9"/>
				</g>
				<line id="_Line_7" class="st3" x1="13.2" y1="23" x2="15.4" y2="27.4"/>
				<g id="_Group_6">
					
						<ellipse id="_Ellipse_" transform="matrix(0.8503 -0.5264 0.5264 0.8503 -1.9946 21.3486)" class="st0" cx="36.5" cy="14.2" rx="6" ry="4.8"/>
					
						<ellipse id="_Ellipse_2" transform="matrix(0.8503 -0.5264 0.5264 0.8503 -1.9946 21.3486)" class="st3" cx="36.5" cy="14.2" rx="6" ry="4.8"/>
					<path id="_Path_10" class="st3" d="M42,14.7c-1.9,0.4-3.8-0.8-4.2-2.8c-0.2-1,0-2.1,0.7-2.9"/>
					<line id="_Line_8" class="st3" x1="31.4" y1="17.4" x2="25.7" y2="21.1"/>
				</g>
				<path id="_Path_11" class="st3" d="M25.3,18.4c0,0-3.4-7.4,1.8-12.5c2.2,1.4,3.9,3.4,4.9,5.8"/>
				<polyline id="_Path_12" class="st2" points="52,13.3 56.6,21.4 56.7,21.4 61.5,30.1 				"/>
				<path id="_Path_13" class="st3" d="M58.5,31.8l-3.1-5.6c-1.4,0.8-3.2,0.3-4-1.1c-0.8-1.4-0.3-3.2,1.1-4l-4-6.9
					c-4.8,2.8-6.8,8.7-4.5,13.8"/>
			</g>
		</g>
	</g>
</g>
</svg>
`;
  export const FoodDishesColor5 = () : string => `<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 21.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 64 64" style="enable-background:new 0 0 64 64;" xml:space="preserve">
<style type="text/css">
	.st0{fill:#F26756;}
	.st1{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke-dasharray:1.000000e-02,7;}
	.st2{fill:#F1EDDB;}
	.st3{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;}
	.st4{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-miterlimit:10;}
	.st5{fill:#F06A54;}
	.st6{fill:none;stroke:#262525;stroke-width:2;stroke-miterlimit:10;}
</style>
<title>Asset 5</title>
<g id="Layer_2">
	<g id="Layer_1-2">
		<g id="_Group_">
			<g id="_Group_2">
				<path id="_Path_" class="st0" d="M19.7,57.2v0.1c-0.5,1.5,0.3,3.2,1.8,3.7c0.3,0.1,0.6,0.2,0.9,0.1h20.8c1.6,0,2.9-1.3,2.9-2.9
					c0-0.3,0-0.6-0.1-0.9v-0.1"/>
				<path id="_Path_2" class="st1" d="M19.1,60.9l-0.6-0.2c-16.1-5.8-17-21.7-17-22.4"/>
				<path id="_Path_3" class="st2" d="M5.2,38.1c0,0,0.6,14.1,14.5,19.1H46c14-5,14.5-19.1,14.5-19.1"/>
				<path id="_Path_4" class="st3" d="M5.2,38.1c0,0,0.6,14.1,14.5,19.1H46c14-5,14.5-19.1,14.5-19.1"/>
				<g id="_Group_3">
					<path id="_Path_5" class="st4" d="M11.8,26.9c0,0.7,0.1,1.5,0.4,2.2"/>
					<path id="_Path_6" class="st4" d="M11.8,26.9c0-3.7,3-6.7,6.7-6.7c0.6,0,1.2,0.1,1.7,0.2"/>
					<path id="_Path_7" class="st4" d="M11.8,26.9H7.1c-2.2,0-4-1.8-4-4c0-1.2,0.6-2.4,1.6-3.2c-1.8-1.4-2.1-3.9-0.7-5.7
						c0.9-1.2,2.5-1.8,4-1.5l0,0c-0.7-2.1,0.4-4.4,2.5-5.2c1.3-0.5,2.7-0.2,3.8,0.6c0.5-2.2,2.6-3.6,4.8-3.1
						c1.5,0.3,2.8,1.5,3.1,3.1c1.8-1.3,4.2-0.9,5.5,0.8c0.5,0.5,0.9,1.2,1,1.9"/>
					<line id="_Path_8" class="st4" x1="8" y1="12.5" x2="9.2" y2="13.6"/>
					<path id="_Path_9" class="st4" d="M14.2,7.9c-0.2,0.9-0.1,1.8,0.4,2.5"/>
					<path id="_Path_10" class="st4" d="M22.1,7.8c0.2,1,0,1.9-0.5,2.8"/>
				</g>
				<g id="_Group_4">
					<path id="_Path_11" class="st3" d="M60.6,32c-0.5-5.3-2.3-10.5-5.4-14.9C45.3,4.4,36.5,7,36.5,7l12.8,16.5
						c0.7,0.9,0.6,2.2-0.3,3c-0.8,0.6-1.9,0.6-2.7,0L29.9,13.6c0,0-2.1,7,6.5,15.6"/>
					<path id="_Path_12" class="st4" d="M39.4,21c2.2-0.5,4-2.3,4.5-4.5"/>
					<path id="_Path_13" class="st4" d="M35,17.6c0,0,3.8-0.6,5.5-5.5"/>
					<path id="_Path_14" class="st4" d="M43.4,24.2c1.8-0.5,3.2-1.9,3.6-3.7"/>
				</g>
				<path id="_Path_15" class="st4" d="M21.1,32.2c-1.5-5.3,0.7-11,5.6-12.3"/>
				<path id="_Path_16" class="st5" d="M24.4,25.1c-0.6,1.2-1,2.5-1,3.8h8.7c-1.8-2.4-4.7-6.2-4.7-6.2C26.2,23,25.1,23.9,24.4,25.1z
					"/>
				<path id="_Path_17" class="st0" d="M60.5,38.1H5.1c-1.6,0-3-1.3-3-3l0,0c0-1.6,1.3-3,3-3c0,0,0,0,0,0h55.4c1.6,0,3,1.3,3,3
					c0,0,0,0,0,0l0,0C63.5,36.8,62.2,38.1,60.5,38.1z"/>
				<path id="_Path_18" class="st6" d="M8.5,23.5c0,0,3.1-11.6,16.9-8.7"/>
				<path id="_Path_19" class="st1" d="M58.2,14.9L58.2,14.9C46.8,0.3,35.9,3.3,35.5,3.4"/>
			</g>
		</g>
	</g>
</g>
</svg>
`;
  export const FoodDishesColor6 = () : string => `<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 21.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 64 64" style="enable-background:new 0 0 64 64;" xml:space="preserve">
<style type="text/css">
	.st0{fill:#FBAB1A;}
	.st1{fill:#F1EDDB;}
	.st2{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;}
	.st3{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke-dasharray:1.000000e-02,7;}
</style>
<title>Asset 6</title>
<g id="Layer_2">
	<g id="Layer_1-2">
		<g id="_Group_">
			<g id="_Group_2">
				<path id="_Path_" class="st0" d="M20.3,57.9V58c-0.5,1.5,0.4,3.2,1.9,3.6c0.3,0.1,0.5,0.1,0.8,0.1h20.5c1.6,0,2.9-1.4,2.9-3
					c0-0.3,0-0.5-0.1-0.8v-0.1"/>
				<path id="_Path_2" class="st1" d="M6,39.1c0,0,0.6,13.9,14.3,18.8h25.9C60,53,60.5,39.1,60.5,39.1"/>
				<path id="_Path_3" class="st2" d="M6,39.1c0,0,0.6,13.9,14.3,18.8h25.9C60,53,60.5,39.1,60.5,39.1"/>
				<g id="_Group_3">
					<path id="_Path_4" class="st2" d="M5.2,30.1c-0.7-5.7,2.6-11.1,7.9-13.1"/>
					<path id="_Path_5" class="st2" d="M8.5,30.1c-0.6-3.8,1.2-7.5,4.5-9.4"/>
					<path id="_Path_6" class="st2" d="M28.8,17.9c3.5-5.9,11.1-7.8,17-4.3c5.7,3.4,7.7,10.7,4.5,16.5"/>
					<path id="_Path_7" class="st2" d="M32.3,18.6c2.9-4.1,8.6-5,12.7-2.1s5,8.6,2.1,12.7c-0.2,0.3-0.5,0.6-0.7,0.9"/>
					<path id="_Path_8" class="st2" d="M16.4,24.4c-2.9-6.2-0.2-13.6,6.1-16.5c4.3-2,9.4-1.3,13.1,1.7"/>
					<path id="_Path_9" class="st2" d="M39.9,17.5c0.3,2.3,0,4.7-1,6.8"/>
					<path id="_Path_10" class="st2" d="M19.3,21.3c-1.2-4.6,1.6-9.3,6.2-10.5c2.1-0.5,4.2-0.3,6.1,0.7"/>
					<path id="_Path_11" class="st2" d="M36.2,18.2c0.1,0.9,0.1,1.9-0.1,2.8"/>
					<path id="_Path_12" class="st2" d="M53.4,18.7c4.7,1,8,5.2,8,10c0,0.5,0,1-0.1,1.4"/>
					<path id="_Path_13" class="st2" d="M54,22c3.2,1.3,5.1,4.7,4.4,8.1"/>
					<g id="_Group_4">
						<path id="_Path_14" class="st2" d="M38.2,30.1c-0.4-5.8-5.4-10.2-11.2-9.8c-5.2,0.4-9.4,4.5-9.8,9.8"/>
						<path id="_Path_15" class="st2" d="M20.5,30.1c0.4-4,3.9-6.9,7.9-6.5c3.4,0.3,6.1,3,6.5,6.5"/>
					</g>
				</g>
				<path id="_Path_16" class="st0" d="M60.6,39.1H6c-1.6,0-2.9-1.3-2.9-2.9l0,0c0-1.6,1.3-2.9,2.9-2.9h54.6c1.6,0,2.9,1.3,2.9,2.9
					l0,0C63.5,37.8,62.2,39.1,60.6,39.1z"/>
				<path id="_Compound_Path_" class="st3" d="M8.3,15.6c-4.2,3-6.8,7.9-6.8,13 M37.8,6.9C31,1.2,21,2.2,15.3,9
					c-0.9,1.1-1.6,2.2-2.2,3.5 M53.8,16.7C51.1,11.3,45.6,8,39.6,8"/>
			</g>
		</g>
	</g>
</g>
</svg>
`;
  export const FoodDishesColor7 = () : string => `<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 21.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 64 64" style="enable-background:new 0 0 64 64;" xml:space="preserve">
<style type="text/css">
	.st0{fill:#FBAB1A;}
	.st1{fill:#849B3B;}
	.st2{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-miterlimit:10;}
	.st3{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;}
	.st4{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke-dasharray:1.000000e-02,7;}
</style>
<title>Asset 7</title>
<g id="Layer_2">
	<g id="Layer_1-2">
		<g id="_Group_">
			<g id="_Group_2">
				<path id="_Path_" class="st0" d="M47.3,41.9c-3.5,0.6-7.1,0.4-10.5-0.5c-3.4-0.9-6.9-1.5-10.4-1.9c-2.8-0.2-5.6,0.2-8.2,1.3
					c1.3,4.4,4,9.9,10.1,12h20.1c8.3-3,10.4-12.2,10.9-16.1C55.3,38.3,51.5,41,47.3,41.9z"/>
				<path id="_Path_2" class="st1" d="M28.3,52.8L28.3,52.8c-0.4,1.3,0.3,2.5,1.4,2.9c0.2,0.1,0.5,0.1,0.7,0.1h15.9
					c1.2,0,2.2-1,2.2-2.2c0-0.2,0-0.5-0.1-0.7v-0.1"/>
				<g id="_Group_3">
					<g id="_Group_4">
						<path id="_Path_3" class="st2" d="M51.6,21.9c-0.1-1.6,0.4-3.2,1.5-4.5c1.1,1,1.9,2.3,2.3,3.8c0.8-1.3,1.8-2.6,2.9-3.7
							c0.4,0.8,1.3,1.2,2.1,1l0.9-0.2c0,0.4-0.1,0.7-0.1,1c-0.1,0.8,0.4,1.6,1.2,1.9c-0.8,1-3.1,3.3-3.1,3.3c1.3,0.3,2.6,1,3.6,1.8
							c-1,1-2.4,1.7-3.8,1.8"/>
					</g>
					<path id="_Path_4" class="st2" d="M56.8,23.1l-1.7,2c-1.3,1.4-1.2,3.6,0.2,4.8c0.1,0.1,0.2,0.2,0.3,0.2"/>
				</g>
				<path id="_Path_5" class="st3" d="M17.2,34.8c0,0,0.4,14.2,11.1,18h20.1c10.7-3.8,11.1-18,11.1-18"/>
				<path id="_Path_6" class="st3" d="M17.2,34.8c0,0,0.4,14.2,11.1,18h20.1c10.7-3.8,11.1-18,11.1-18"/>
				<g id="_Group_5">
					<path id="_Path_7" class="st3" d="M9,51.8c-2.4-3.7-4.8-11.3-4.8-20"/>
					<path id="_Path_8" class="st3" d="M23,55.8H10.6c-0.9,0-1.6-0.7-1.6-1.6v-2.4h10.7"/>
					<path id="_Path_9" class="st3" d="M26.7,25.8h-9.8c-2.3,0-4.4,0.4-5.6,2.3l-2.4,4.1l-4-6.1c-0.5-0.7-0.7-1.5-0.7-2.4v-0.1
						c0-0.8,0.6-1.4,1.4-1.4l0,0H29c1.3,0,2.3,1,2.3,2.3c0,0,0,0,0,0c0,1.9-0.2,3.7-0.7,5.6"/>
				</g>
				<g id="_Group_6">
					<path id="_Path_10" class="st3" d="M36.3,16.6l0.4-0.4c0.9-0.9,0.9-2.5,0-3.4l-0.4-0.4l-0.4-0.4c-0.9-0.9-0.9-2.5,0-3.4
						l0.4-0.4"/>
					<path id="_Path_11" class="st3" d="M41,16.6l0.4-0.4c0.9-0.9,0.9-2.5,0-3.4L41,12.5l-0.4-0.4c-0.9-0.9-0.9-2.5,0-3.4L41,8.3"/>
					<path id="_Path_12" class="st3" d="M45.6,16.6l0.4-0.4c0.9-0.9,0.9-2.5,0-3.4l-0.4-0.4l-0.4-0.4c-0.9-0.9-0.9-2.5,0-3.4
						l0.4-0.4"/>
				</g>
				<path id="_Path_13" class="st3" d="M35.3,27.7c-0.5-0.5-0.5-1.4,0-1.9l2.2-2.2c0.5-0.5,1.4-0.5,1.9,0l2.3,2.3
					c0.5,0.5,0.5,1.4,0,1.9"/>
				<path id="_Path_14" class="st3" d="M42.3,23.5l1.4-1.5c0.7-0.7,1.8-0.7,2.5,0l3,3c0.7,0.7,0.7,1.8,0,2.5"/>
				<path id="_Path_15" class="st1" d="M59.6,34.8H17.1c-1.2,0-2.3-1-2.3-2.2l0,0c0-1.3,1-2.3,2.3-2.3h42.4c1.2,0,2.3,1,2.3,2.3l0,0
					C61.8,33.7,60.8,34.7,59.6,34.8z"/>
				<path id="_Path_16" class="st3" d="M59.6,34.8H17.1c-1.2,0-2.3-1-2.3-2.2l0,0c0-1.3,1-2.3,2.3-2.3h42.4c1.2,0,2.3,1,2.3,2.3l0,0
					C61.8,33.7,60.8,34.7,59.6,34.8z"/>
				<path id="_Path_17" class="st4" d="M0.8,31.8c0,9.3,2.5,16.8,4.8,20.9"/>
			</g>
		</g>
	</g>
</g>
</svg>
`;
  export const FoodDishesColor8 = () : string => `<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 21.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 64 64" style="enable-background:new 0 0 64 64;" xml:space="preserve">
<style type="text/css">
	.st0{fill:#849B3B;}
	.st1{fill:#FBAB1A;}
	.st2{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-miterlimit:10;}
	.st3{fill:#F26756;}
	.st4{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke-dasharray:1.000000e-02,7;}
</style>
<title>Asset 8</title>
<g id="Layer_2">
	<g id="Layer_1-2">
		<g id="_Group_">
			<g id="_Group_2">
				<path id="_Path_" class="st0" d="M46.6,58.1V60c0,1.4-1.2,2.6-2.6,2.6H20c-1.4,0-2.6-1.2-2.6-2.6v-1.8"/>
				<path id="_Path_2" class="st1" d="M40.6,58.3h4.1c6.7,0,12.4-5.1,13.1-11.8c0-0.5,0-0.8,0-0.8h3.2c1,0,1.9-0.8,1.9-1.8
					c0,0,0,0,0,0l0,0c0-1-0.8-1.9-1.9-1.9H2.9c-1,0-1.9,0.8-1.9,1.9l0,0c0,1,0.8,1.9,1.9,1.9h3.2c0,0,0,0.3,0,0.8
					c0.7,6.7,6.4,11.8,13.1,11.8H40.6z"/>
				<g id="_Group_3">
					<path id="_Path_3" class="st2" d="M26.1,15c-0.5-0.4-0.9-0.9-1.1-1.5c-0.6-1.5-0.4-3.2,0.5-4.5c0.6-1,0.9-2.1,1-3.2
						c0-0.6,0-1.1-0.2-1.7c-0.3-0.6-0.7-1.2-1.2-1.7"/>
					<path id="_Path_4" class="st2" d="M32.5,15c0,0-2.8-2.1-0.6-6c2.6-4.6-0.4-6.3-0.4-6.5"/>
					<path id="_Path_5" class="st2" d="M38.9,15c0,0-2.8-2.1-0.6-6c0.6-1,0.9-2.1,1-3.2c0.1-1.3-0.4-2.5-1.4-3.4"/>
				</g>
				<path id="_Path_6" class="st2" d="M40.6,58.3h4.1c6.7,0,12.4-5.1,13.1-11.8c0-0.5,0-0.8,0-0.8h3.2c1,0,1.9-0.8,1.9-1.8
					c0,0,0,0,0,0l0,0c0-1-0.8-1.9-1.9-1.9H2.9c-1,0-1.9,0.8-1.9,1.9l0,0c0,1,0.8,1.9,1.9,1.9h3.2c0,0,0,0.3,0,0.8
					c0.7,6.7,6.4,11.8,13.1,11.8H40.6z"/>
				<g id="_Group_4">
					<g id="_Group_5">
						<path id="_Path_7" class="st3" d="M29.1,25.2c-1.6-1.6-4.3-1.3-5.7-1c-2.7,0.7-5.2,2-7.4,3.9c1.2-0.6,2.5-1.1,3.9-1.4
							c1.7-0.4,4.7-0.7,6.6,1.1s1.5,4.9,1.1,6.6c-0.3,1.4-0.8,2.8-1.5,4c1.9-2.1,3.3-4.7,4-7.5C30.4,29.4,30.7,26.8,29.1,25.2z"/>
					</g>
					<path id="_Path_8" class="st2" d="M6.2,41.9c-0.6-4.3,1.7-10,6.3-14.5c6.4-6.4,14.7-8.3,18.7-4.3s2.1,12.4-4.3,18.7L26.7,42"/>
					<g id="_Group_6">
						<line id="_Line_" class="st2" x1="15" y1="36.5" x2="16.6" y2="38.1"/>
						<line id="_Line_2" class="st2" x1="17.2" y1="32.1" x2="22.2" y2="37.1"/>
						<line id="_Line_3" class="st2" x1="21.6" y1="29.8" x2="24.4" y2="32.6"/>
					</g>
				</g>
				<g id="_Group_7">
					<line id="_Line_4" class="st2" x1="41.9" y1="35.1" x2="38.5" y2="38.4"/>
					<line id="_Line_5" class="st2" x1="37.9" y1="33.1" x2="36.1" y2="35"/>
				</g>
				<path id="_Path_9" class="st2" d="M57.7,38.4c-0.4-9.7-12.1-20.3-23.2-19"/>
				<path id="_Path_10" class="st2" d="M33.3,27.6c3.6-0.6,8.1,1.1,11.5,4.6c2.7,2.6,4.4,6.1,4.7,9.8"/>
				<path id="_Path_11" class="st4" d="M22.2,17.9c-4.6,1.1-8.9,3.5-12.2,7C6.3,28.4,3.8,33,2.8,38.1"/>
			</g>
		</g>
	</g>
</g>
</svg>
`;
  export const FoodDishesColor9 = () : string => `<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 21.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 64 64" style="enable-background:new 0 0 64 64;" xml:space="preserve">
<style type="text/css">
	.st0{fill:#F7CF13;}
	.st1{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke-dasharray:1.000000e-02,7;}
	.st2{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;}
	.st3{fill:none;stroke:#262525;stroke-width:2;stroke-linecap:round;stroke-miterlimit:10;}
	.st4{fill:#849B3B;}
</style>
<title>Asset 9</title>
<g id="Layer_2">
	<g id="Layer_1-2">
		<g id="_Group_">
			<g id="_Group_2">
				<path id="_Path_" class="st0" d="M39.4,33c-6.6-5.6-15.8-11.7-24-9c-22.4,7.5,3.9,19.9,22,14.4c5.2-1.6,8.3,2.9,9.5-1
					C48.1,33.3,42.1,35.2,39.4,33z"/>
				<path id="_Path_2" class="st1" d="M13.1,13.1c10.5-10.5,27.4-10.5,37.9,0"/>
				<path id="_Path_3" class="st1" d="M50.9,50.9c-10.5,10.5-27.4,10.5-37.9,0"/>
				
					<ellipse id="_Ellipse_" transform="matrix(0.8486 -0.5291 0.5291 0.8486 -11.9823 21.8166)" class="st2" cx="32.1" cy="31.8" rx="31" ry="31"/>
				<path id="_Path_4" class="st3" d="M39.4,33c-6.6-5.6-15.8-11.7-24-9c-22.4,7.5,3.9,19.9,22,14.4c5.2-1.6,8.3,2.9,9.5-1
					C48.1,33.3,42.1,35.2,39.4,33z"/>
				<path id="_Path_5" class="st3" d="M13.6,27.8c0.3,0.8,0,1.6-0.8,2s-1.6,0-2-0.8l0,0"/>
				<path id="_Path_6" class="st3" d="M46.5,41.8c0.9,1.3,2.3,2.1,3.9,2.3c0.4,0,0.7,0,1.1,0l0,0c-0.1-3.8,0.8-7.6,2.6-10.9l0,0
					c-0.4-0.3-0.9-0.5-1.3-0.6c-1.5-0.4-3.2-0.2-4.6,0.6"/>
				<path id="_Path_7" class="st3" d="M14.9,24.1c0,0,5.6,4.5-0.2,13.5"/>
				<path id="_Path_8" class="st3" d="M39.8,29.6c0.6-1.6,0.1-4.3-3.4-5.7c-5-1.9-6.3-5.5-6.3-5.5c-7.4,3.5-10.6-2.6-10.6-2.6
					l-4.9,5.3"/>
				<path id="_Path_9" class="st3" d="M17.5,38.5c0,0-0.5,6.5,4.6,9.7l1.4-3.4c0,0,4.5,2.1,5.8-5.1"/>
				<path id="_Path_10" class="st3" d="M49.4,16.2c-2.7,3.4-7.7,3.9-11,1.1c-2.4-2-3.4-5.1-2.6-8.1"/>
				<path id="_Path_11" class="st4" d="M39.4,12.1c0.2,0.1,0.2,0.4,0.1,0.5c0,0-0.1,0.1-0.1,0.1c-0.6,0.3-0.7,1-0.4,1.6
					c0.2,0.3,0.5,0.5,0.8,0.6c0.7,0.1,1.3,0.5,1.8,1c0.5,0.5,1.2,0.5,1.7,0c0.2-0.2,0.4-0.6,0.3-0.9c0-0.2,0.2-0.4,0.4-0.4
					c0.1,0,0.1,0,0.1,0c0.5,0.3,1.2,0.1,1.6-0.4c0,0,0,0,0,0c0.3-0.6,0.1-1.3-0.4-1.6c-1.5-1-3.1-1.8-4.8-2.4
					c-0.5-0.3-1.2-0.1-1.5,0.4C38.7,11.1,38.8,11.8,39.4,12.1L39.4,12.1z"/>
				<path id="_Path_12" class="st3" d="M31.4,55.8c-0.5-4.3,2.7-8.1,7-8.6c3.1-0.3,6.1,1.2,7.6,3.9"/>
				<path id="_Path_13" class="st4" d="M41.3,51.6c-0.2,0-0.4-0.1-0.5-0.3c0,0,0-0.1,0-0.2c0.2-0.6-0.2-1.3-0.8-1.4
					c-0.3-0.1-0.7,0-1,0.2c-0.6,0.4-1.2,0.6-1.9,0.6c-0.6,0-1.2,0.5-1.2,1.2c0,0.3,0.1,0.7,0.4,0.9c0.1,0.2,0.1,0.4,0,0.5
					c0,0-0.1,0.1-0.1,0.1c-0.6,0.2-1,0.8-0.8,1.4c0,0,0,0,0,0c0.2,0.6,0.8,0.9,1.4,0.8c1.8-0.4,3.5-1,5.1-1.7
					c0.5-0.2,0.8-0.9,0.5-1.4c-0.2-0.4-0.6-0.6-1-0.6L41.3,51.6z"/>
			</g>
		</g>
	</g>
</g>
</svg>
`;
  