/**
 * Generated by scripts/generate-logos.js
 * DO NOT EDIT!
 */

import { storiesOf } from '@storybook/react-native';
import { Story, UseCase } from '@react-pakistan/react-native-commons-collection/views';
import React, { ReactElement } from 'react';
import { LogoWrapper, StyledScrollView, StyledView, TextWrapper } from './styled';
import { Logo } from '../src/logo';

storiesOf('Logo', module)
  .add('bitcoin-color', () : ReactElement => (
    <Story>
      <UseCase
        text="Logo => bitcoin-color"
      >
        <StyledScrollView>
          <StyledView>
            <LogoWrapper>
              <Logo logo="BitcoinColor1" />
                <TextWrapper>
                  BitcoinColor1
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="BitcoinColor10" />
                <TextWrapper>
                  BitcoinColor10
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="BitcoinColor11" />
                <TextWrapper>
                  BitcoinColor11
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="BitcoinColor12" />
                <TextWrapper>
                  BitcoinColor12
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="BitcoinColor13" />
                <TextWrapper>
                  BitcoinColor13
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="BitcoinColor14" />
                <TextWrapper>
                  BitcoinColor14
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="BitcoinColor15" />
                <TextWrapper>
                  BitcoinColor15
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="BitcoinColor16" />
                <TextWrapper>
                  BitcoinColor16
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="BitcoinColor17" />
                <TextWrapper>
                  BitcoinColor17
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="BitcoinColor18" />
                <TextWrapper>
                  BitcoinColor18
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="BitcoinColor19" />
                <TextWrapper>
                  BitcoinColor19
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="BitcoinColor2" />
                <TextWrapper>
                  BitcoinColor2
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="BitcoinColor20" />
                <TextWrapper>
                  BitcoinColor20
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="BitcoinColor21" />
                <TextWrapper>
                  BitcoinColor21
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="BitcoinColor22" />
                <TextWrapper>
                  BitcoinColor22
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="BitcoinColor23" />
                <TextWrapper>
                  BitcoinColor23
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="BitcoinColor24" />
                <TextWrapper>
                  BitcoinColor24
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="BitcoinColor25" />
                <TextWrapper>
                  BitcoinColor25
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="BitcoinColor26" />
                <TextWrapper>
                  BitcoinColor26
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="BitcoinColor27" />
                <TextWrapper>
                  BitcoinColor27
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="BitcoinColor28" />
                <TextWrapper>
                  BitcoinColor28
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="BitcoinColor29" />
                <TextWrapper>
                  BitcoinColor29
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="BitcoinColor3" />
                <TextWrapper>
                  BitcoinColor3
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="BitcoinColor30" />
                <TextWrapper>
                  BitcoinColor30
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="BitcoinColor31" />
                <TextWrapper>
                  BitcoinColor31
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="BitcoinColor32" />
                <TextWrapper>
                  BitcoinColor32
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="BitcoinColor33" />
                <TextWrapper>
                  BitcoinColor33
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="BitcoinColor34" />
                <TextWrapper>
                  BitcoinColor34
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="BitcoinColor35" />
                <TextWrapper>
                  BitcoinColor35
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="BitcoinColor36" />
                <TextWrapper>
                  BitcoinColor36
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="BitcoinColor4" />
                <TextWrapper>
                  BitcoinColor4
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="BitcoinColor5" />
                <TextWrapper>
                  BitcoinColor5
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="BitcoinColor6" />
                <TextWrapper>
                  BitcoinColor6
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="BitcoinColor7" />
                <TextWrapper>
                  BitcoinColor7
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="BitcoinColor8" />
                <TextWrapper>
                  BitcoinColor8
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="BitcoinColor9" />
                <TextWrapper>
                  BitcoinColor9
                </TextWrapper>
              </LogoWrapper>
          </StyledView>
        </StyledScrollView>
      </UseCase>
    </Story>
  ))
.add('misc-color', () : ReactElement => (
    <Story>
      <UseCase
        text="Logo => misc-color"
      >
        <StyledScrollView>
          <StyledView>
            <LogoWrapper>
              <Logo logo="MiscColor1" />
                <TextWrapper>
                  MiscColor1
                </TextWrapper>
              </LogoWrapper>
          </StyledView>
        </StyledScrollView>
      </UseCase>
    </Story>
  ))
.add('vintage-color', () : ReactElement => (
    <Story>
      <UseCase
        text="Logo => vintage-color"
      >
        <StyledScrollView>
          <StyledView>
            <LogoWrapper>
              <Logo logo="VintageColor1" />
                <TextWrapper>
                  VintageColor1
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="VintageColor10" />
                <TextWrapper>
                  VintageColor10
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="VintageColor11" />
                <TextWrapper>
                  VintageColor11
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="VintageColor12" />
                <TextWrapper>
                  VintageColor12
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="VintageColor13" />
                <TextWrapper>
                  VintageColor13
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="VintageColor14" />
                <TextWrapper>
                  VintageColor14
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="VintageColor15" />
                <TextWrapper>
                  VintageColor15
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="VintageColor16" />
                <TextWrapper>
                  VintageColor16
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="VintageColor2" />
                <TextWrapper>
                  VintageColor2
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="VintageColor3" />
                <TextWrapper>
                  VintageColor3
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="VintageColor4" />
                <TextWrapper>
                  VintageColor4
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="VintageColor5" />
                <TextWrapper>
                  VintageColor5
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="VintageColor6" />
                <TextWrapper>
                  VintageColor6
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="VintageColor7" />
                <TextWrapper>
                  VintageColor7
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="VintageColor8" />
                <TextWrapper>
                  VintageColor8
                </TextWrapper>
              </LogoWrapper><LogoWrapper>
              <Logo logo="VintageColor9" />
                <TextWrapper>
                  VintageColor9
                </TextWrapper>
              </LogoWrapper>
          </StyledView>
        </StyledScrollView>
      </UseCase>
    </Story>
  ))
